#!/bin/bash

set -x

HOMEDIR=/home/steamsrv
STEAMCMD=/home/steamsrv/steamcmd/steamcmd.sh

if [ "x${APPID}" = "x" ]; then
	echo "ERROR: Need to set APPID"
	exit 1
fi
if [ "x${APPDIR}" = "x" ]; then 
	echo "ERROR: Need to set APPDIR"
	exit 1
fi
if [ "x${STEAM_USER}" = "x" ]; then
	echo "ERROR: Need to set STEAM_USER"
	exit 1
fi
if ! [ "x${STEAMCMD_OPTS}" = "x" ]; then
	STEAMCMD_OPTS="\"${STEAMCMD_OPTS}\""
fi

cd ${HOMEDIR}

${STEAMCMD} +force_install_dir ${APPDIR} +login ${STEAM_USER} ${STEAM_PASSWORD} +app_update ${APPID} ${STEAMCMD_OPTS} validate +quit

