#!/bin/bash

cd ${APPDIR}

if ! [ "x${APP_SERVER_TOKEN}" = "x" ]; then
	STEAM_SERVER_TOKEN="+sv_setsteamaccount ${APP_SERVER_TOKEN}"
fi

if [ "$USE_SRCDS" = "true" ]; then
	echo "running: ./srcds_run -console -game ${APP_GAME_NAME} -nohltv ${STEAM_SERVER_TOKEN} +maxplayers ${APP_SERVER_MAXPLAYERS} +map ${APP_SERVER_MAP} -port ${APP_SERVER_PORT}"
	./srcds_run -console -game ${APP_GAME_NAME} -nohltv ${STEAM_SERVER_TOKEN} +maxplayers ${APP_SERVER_MAXPLAYERS} +map ${APP_SERVER_MAP} -port ${APP_SERVER_PORT}
else
	echo "Unknown Server Startup Usage"
	exit 1
fi


