#!/bin/bash

cd ${APPDIR}

if [ "$USE_SRCDS" = "true" ]; then
	./srcds_run -console -game ${APP_GAME_NAME} +maxplayers ${APP_SERVER_MAXPLAYERS} +map ${APP_SERVER_MAP} -port ${APP_SERVER_PORT}
else
	echo "Unknown Server Startup Usage"
	exit 1
fi


